### PR TITLE
Fix yLabel width calculation to better align x-scale

### LINKED ISSUE #274: y-Axis labels are cut off if the top label is not the widest label
### Describe Your Environment

**What version of victory-native-xl are you using?** 
v40.2.0
**What version of React and React Native are you using?**
v18.3.0, v74.1
**What version of Reanimated and React Native Skia are you using?**
3.11.0, 1.2.3
**Are you using Expo or React Native CLI?**
no
**What platform are you on?** (e.g., iOS, Android)
ios, but happens on both
### Describe the Problem

Labels are cut off if your top level y label is not the widest label. The most common case I have for this is when the Y domain is small and the ticks may contain decimal values.
For example, if my domain is `0` - `2`, the automatically generated tick values are `0, 0.5, 1, 1.5, 2`. This is great, however in the `transformInputData` function (specifically line `176`) only looks at the top value assuming it will be the largest.

I think this may have been done as a speed hack to not calculate the width of the labels a few different times, but I don't think the outcome is worth the potential speed increase, or at least add an option to force the calculation of all labels.

Here's an example showing this behavior 
image
As you can see, this is problematic since not only is the preceding `0` cut off, but the `.` as well, leading to some confusing domains.
 
Sample code to reproduce:
```tsx

const d = []
for (let i = 0; i < 400; i++) {
  d.push({ x: i, y1: Math.random() * 2, y2:  Math.random() * 2 - 0.2 })
}

const Chart = () => {
  return (
    <View style={{ height: 300, width: 400, backgroundColor: "black" }}>
      <CartesianChart
        data={d}
        xKey="x"
        yKeys={["y1","y2"]}
        axisOptions={{ font }}
      >
        {({ points }) => (
          <>
            <Scatter radius={1} points={points.y1} color="purple" />    
            <Line strokeWidth={1} points={points.y1} color="white" />
          </>
      </CartesianChart>
    </View>
  )
}
```
**Expected behavior:** [What you expect to happen]
Label padding is calculated using the widest width label.

**Actual behavior:** [What actually happens]
Label padding is only calculated using the top most label, which isn't necessarily the widest label.

### PR DESCRIPTION
**Pull request by owattenmaker**
### Description

Fixes #274 

(builds off of #290, can update pr once that gets merged in)

Basically moves the `yTicksNormalized` calculation to `transformInputData` so that we know what all the ticks will be, instead of just guessing what the top tick will be which can be both wrong and misinformed.

Here's an extreme example of what this fixes: 
image
notice how now it doesn't cut off any of the tick values, even when they're absurdly long

#### Type of Change

- [x] Bug fix (non-breaking change which fixes an issue)

### How Has This Been Tested?

In example app. Added example app option to play around with tick values directly.

### CODE REVIEW

File: lib/src/cartesian/utils/transformInputData.ts [hunk 1]
```diff
@@ -229,6 +248,13 @@ export const transformInputData = <
     padEnd:
       typeof domainPadding === "number" ? domainPadding : domainPadding?.right,
   });
+
+  // Normalize xTicks values either via the d3 scaleLinear ticks() function or our custom downSample function
+  // For consistency we do it here, so we have both y and x ticks to pass to the axis generator
```
Comment (zibs) [inline lib/src/cartesian/utils/transformInputData.ts:253]: consistency 🙏🏻

**Review by zibs — COMMENTED** [review]
This is looking really good! Just a few small cleanups I think! Thanks so much!

File: lib/src/cartesian/components/CartesianAxis.tsx
Comment (zibs) [inline lib/src/cartesian/components/CartesianAxis.tsx:1]: Can you check the warning in this file too?

File: example/app/axis-configuration.tsx [hunk 2]
```diff
@@ -0,0 +1,346 @@
...
+  const ticksX = useMemo(
+    () => parseTickValues(xAxisValues) ?? [0, 10],
+    [xAxisValues],
+  );
+  const ticksY = useMemo(
+    () => parseTickValues(yAxisValues) ?? [0, 10],
+    [yAxisValues],
+  );
+
+  const data = useMemo(() => DATA(ticksX, ticksY), [xAxisValues, yAxisValues]);
```
[the remark this answers is not in the document]
Comment (owattenmaker) [reply example/app/axis-configuration.tsx]: updated. the warning is annoying to look at, but might actually be wrong since comparing references to each other for memo'd values can produce weird results, whereas here i'm doing string comparison. not a big deal tho, this is just generating random data within the confines of the given ticks

**Review by zibs — APPROVED** [review]
awesome, thanks again!
